- name: get hosts facts
  hosts: all
  gather_facts: yes

- name: build environment
  hosts: localhost
  gather_facts: no
  vars:
    db_name: demo
    virtualenv: '{{ hostvars[inventory_hostname].ansible_env.HOME }}/.virtualenvs/business-to-business-sync-data-env'
  tasks:
    - name: init server environment
      include_role:
        name: 'update_{{ ansible_distribution|lower }}_environment'
    - name: init python environment
      include_role:
        name: create_python_virtualenv
    - name: build postgresql
      include_role:
        name: 'build_postgresql'
    - name: import data to postgresql, step 1
      include_tasks: tasks/import_sku_data.yaml
    - name: insert data to postgresql, step 2
      include_tasks: tasks/import_st_data.yaml
    - name: build oracle environment
      include_tasks: tasks/build_oracle_environment.yaml
    - name: run python scripts
      block:
        - name: fetch data from e1
          include_tasks: tasks/fetch_data_from_e1.yaml
        - name: export data to file
          include_tasks: tasks/export_data_to_file.yaml
        - name: clean up dirty data
          include_tasks: tasks/clean_up_dirty_data.yaml
      vars:
        abs_python_path: '{{ playbook_dir }}/vars/python'
      environment:
        PATH: '{{ virtualenv }}/bin:{{ hostvars[inventory_hostname].ansible_env.PATH }}'
        LD_LIBRARY_PATH: '/opt/oracle/instantclient_21_1'
        PYTHONPATH: '{{ playbook_dir }}/vars/python'
      tags: python
