- name: get hosts facts
  hosts: all
  gather_facts: yes

- name: build environment
  hosts: localhost
  gather_facts: no
  vars:
    db_name: demo
  tasks:
    - name: init server environment
      include_role:
        name: 'update_{{ ansible_distribution|lower }}_environment'
    - name: build postgresql
      include_role:
        name: 'build_postgresql'
    - name: insert test data to postgresql
      include_tasks: tasks/insert_test_data.yaml