- name: install required packages
  apt:
    name:
      - libssl-dev
      - libssl-doc
    state: present
  become: yes

- name: install postgresql
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
    state: present
  become: yes

- name: ensure the postgresql service is running
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: ensure database is created
  community.general.postgresql_db:
    name: '{{ db_name }}'
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    state: present
  become: yes
  become_user: postgres

- name: drop tables
  community.general.postgresql_table:
    db: '{{ db_name }}'
    table: '{{ item }}'
    state: absent
    cascade: yes
  loop:
    - product_list
    - ship_to
  become: yes
  become_user: postgres

- name: create table product list in db
  community.general.postgresql_table:
    db: '{{ db_name }}'
    table: product_list
    columns:
      - product_id bigserial primary key
      - sku varchar(255) not null
      - business_unit varchar(255) not null
      - discontinued boolean
      - created_by varchar(255)
      - created_date timestamp
      - updated_by varchar(255)
      - updated_date timestamp
  become: yes
  become_user: postgres

- name: create table ship to in db
  community.general.postgresql_table:
    db: '{{ db_name }}'
    table: ship_to
    columns:
      - st_id bigserial primary key
      - st bigint not null
      - is_default boolean
      - created_by varchar(255)
      - created_date timestamp
      - updated_by varchar(255)
      - updated_date timestamp
  become: yes
  become_user: postgres

- name: create table casmart research group in db
  community.general.postgresql_table:
    db: '{{ db_name }}'
    table: casmart_research_group
    columns:
      - research_group_id bigserial primary key
      - research_group_name varchar(255) not null
      - research_group_contact_name varchar(255) not null
      - research_group_contact_phone varchar(255) not null
      - sourcing varchar(255) not null
      - created_by varchar(255)
      - created_date timestamp
      - updated_by varchar(255)
      - updated_date timestamp
  become: yes
  become_user: postgres

- name: create table ship to casmart research group in db
  community.general.postgresql_table:
    db: '{{ db_name }}'
    table: ship_to_casmart_research_group
    columns:
      - st_id bigint not null references ship_to
      - research_group_id bigint not null references casmart_research_group
      - created_by varchar(255)
      - created_date timestamp
      - updated_by varchar(255)
      - updated_date timestamp
      - primary key (st_id, research_group_id)
  become: yes
  become_user: postgres

- name: create table list price in db
  community.general.postgresql_table:
    db: '{{ db_name }}'
    table: list_price
    columns:
      - list_price_id bigserial primary key
      - product_id bigint not null
      - list_price numeric not null
      - effective_date timestamp
      - expiration_date timestamp
      - created_by varchar(255)
      - created_date timestamp
      - updated_by varchar(255)
      - updated_date timestamp
  become: yes
  become_user: postgres

- name: create table quote price in db
  community.general.postgresql_table:
    db: '{{ db_name }}'
    table: quote_price
    columns:
      - quote_price_id bigserial primary key
      - quote_price numeric not null
      - quote_type char(1) not null
      - quote_number bigint not null
      - min_order_quantity bigint not null
      - product_id bigint not null
      - st_id bigint not null
      - effective_date timestamp
      - expiration_date timestamp
      - created_by varchar(255)
      - created_date timestamp
      - updated_by varchar(255)
      - updated_date timestamp
  become: yes
  become_user: postgres

- name: create table product discontinued list in db
  community.general.postgresql_table:
    db: '{{ db_name }}'
    table: product_discontinued_list
    columns:
      - sku varchar(255) not null
  become: yes
  become_user: postgres

- name: create table product action list in db
  community.general.postgresql_table:
    db: '{{ db_name }}'
    table: product_action_list
    columns:
      - product_id bigint not null
      - action char(1) not null
  become: yes
  become_user: postgres

- name: create views in db
  community.general.postgresql_query:
    db: '{{ db_name }}'
    path_to_script: vars/postgresql/create_views.sql
    encoding: UTF-8
  become: yes
  become_user: postgres

- name: create user
  community.general.postgresql_user:
    name: '{{ db_user }}'
    password: '{{ db_password }}'
    state: present
  become: yes
  become_user: postgres

- name: ensure user has the access, step 1
  community.general.postgresql_privs:
    db: '{{ db_name }}'
    role: '{{ db_user }}'
    objs: ALL_DEFAULT
    privs: ALL
    type: default_privs
    grant_option: yes
  become: yes
  become_user: postgres

- name: ensure user has the access, step 2
  community.general.postgresql_privs:
    db: '{{ db_name }}'
    role: '{{ db_user }}'
    objs: ALL_IN_SCHEMA
    type: table
    privs: SELECT,INSERT,UPDATE,DELETE,TRIGGER
  become: yes
  become_user: postgres

- name: ensure user has the access, step 3
  community.general.postgresql_privs:
    db: '{{ db_name }}'
    role: '{{ db_user }}'
    objs: ALL_IN_SCHEMA
    type: sequence
    privs: SELECT,UPDATE,USAGE
  become: yes
  become_user: postgres

- name: ensure user does not have unnecessary privileges
  community.general.postgresql_user:
    name: '{{ db_user }}'
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present
  become: yes
  become_user: postgres
