- name: install required packages
  apt:
    name:
      - libssl-dev
      - libssl-doc
    state: present
  become: yes

- name: install postgresql
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
    state: present
  become: yes

- name: ensure the postgresql service is running
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: ensure database is created
  community.general.postgresql_db:
    name: '{{ db_name }}'
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    state: present
  become: yes
  become_user: postgres

- name: ensure user has access to the database
  community.general.postgresql_user:
    db: '{{ db_name }}'
    name: '{{ db_user }}'
    password: '{{ db_password }}'
    priv: ALL
    state: present
  become: yes
  become_user: postgres

- name: ensure user does not have unnecessary privileges
  community.general.postgresql_user:
    name: '{{ db_user }}'
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present
  become: yes
  become_user: postgres
