- name: clean up dirty data
  command: '{{ virtualenv }}/bin/python3 {{ abs_python_path }}/clean_up_dirty_data.py'
  args:
    chdir: '{{ abs_python_path }}'
  register: clean_up_dirty_data_output

- debug:
    var: clean_up_dirty_data_output.stdout_lines