- name: export data to file
  script: '{{ abs_python_path }}/export_data_to_file.py'
  args:
    chdir: '{{ abs_python_path }}'
    executable: '{{ virtualenv }}/bin/python3'
  register: export_data_to_file_output

- debug:
    var: export_data_to_file_output.stdout_lines