- name: fetch data from e1
  command: '{{ virtualenv }}/bin/python3 {{ abs_python_path }}/fetch_data_from_e1.py'
  args:
    chdir: '{{ abs_python_path }}'
  register: fetch_data_from_e1_output

- debug:
    var: fetch_data_from_e1_output.stdout_lines