- name: get absolute path of python scripts
  include_role:
    name: get_absolute_path_of_directory
  vars:
    directory: python
    path: vars/python

- name: run a python script
  script: '{{ abs_python_path }}/fetch_data_from_e1.py'
  args:
    chdir: '{{ abs_python_path }}'
    executable: '{{ virtualenv }}/bin/python3'
  register: fetch_data_from_e1_output

- debug:
    var: fetch_data_from_e1_output.stdout_lines