- name: generate sql script
  command: '{{ virtualenv }}/bin/python3 {{ abs_python_path }}/generate_import_data_sql.py st'
  args:
    chdir: '{{ abs_python_path }}'

- name: import st data
  community.general.postgresql_query:
    db: '{{ db_name }}'
    path_to_script: '{{ abs_postgresql_path }}/import_st_data.sql'
    encoding: UTF-8
  become: yes
  become_user: postgres