- name: generate sql script
  command: '/usr/bin/python3 ./generate_import_data_sql.py {{ item }}'
  args:
    chdir: 'vars/python'
  loop:
    - product sku
    - product ppl
    - st

- name: import product data
  community.postgresql.postgresql_query:
    db: '{{ database_name }}'
    port: '{{ database_port }}'
    path_to_script: 'vars/postgresql/insert_{{ item }}_data.sql'
    as_single_query: no
    encoding: UTF-8
  become: yes
  become_user: postgres
  loop:
    - sku
    - ppl
    - st