- name: get absolute path of python scripts
  include_role:
    name: get_absolute_path_of_directory
  vars:
    directory: python
    path: vars/python

- name: generate sql script
  command: '{{ virtualenv }}/bin/python3 {{ abs_python_path }}/generate_import_data_sql.py sku'
  args:
    chdir: '{{ abs_python_path }}'

- name: import sku data
  community.general.postgresql_query:
    db: '{{ db_name }}'
    path_to_script: vars/postgresql/import_sku_data.sql
    encoding: UTF-8
  become: yes
  become_user: postgres