version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: '%(asctime)s - %(name)s: %(message)s'
  extended:
    format: "%(asctime)s - %(name)s - %(levelname)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: extended
    filename: ../logs/application.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
loggers:
  '':
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
root:
  level: NOTSET
  handlers: [ console, file ]