- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  become: yes
  ignore_errors: yes

- name: update all packages
  apt:
    upgrade: dist
  become: yes

- name: install required packages
  apt:
    name:
      - unzip
      - libssl-dev
      - libssl-doc
      - libaio1
      - python3-venv
      - python3-dev
    state: present
  become: yes

- name: import repository signing keys
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: yes

- name: get ubuntu distribution code
  command: lsb_release -cs
  register: ubuntu_release

- name: add postgresql repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt {{ ubuntu_release.stdout }}-pgdg main
    state: present
    update_cache: yes
  become: yes

- name: install postgresql 12
  apt:
    name:
      - postgresql-12
      - postgresql-contrib-12
      - libpq-dev
      - python3-psycopg2
    state: present
  become: yes